# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: HyungJin.JHJ_AI-Usage-Monitor
PackageVersion: 1.0.10.20261009
InstallerType: exe
Scope: user
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent --version 1.0.10.20261009
  SilentWithProgress: --silent --version 1.0.10.20261009
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: JHJ AI Usage Monitor
  Publisher: HyungJin Ju
  DisplayVersion: 1.0.10.20261009
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/HyungJIn-kr-97/JHJ_AI_USAGE/releases/download/v1.0.10.20261009/JHJ_AI-Usage-Monitor_Setup.exe
  InstallerSha256: 1BB092A7AFF346E89580CC2DB3DC5C7C4E700A272B25C4AEF9A99D2129492079
ManifestType: installer
ManifestVersion: 1.6.0