using System.Text.RegularExpressions;

namespace costats.App.Localization;

/// <summary>
/// 한국어 문안. 키는 화면에 쓰이던 영어 원문 그대로다(Footer* 만 이름 키).
/// 계약: 새 문구를 화면에 더하면 여기에 한 줄을 더한다 — 빠뜨리면 한국어 모드에서도 영어로 나올 뿐 깨지지는 않는다.
/// </summary>
internal static class LocStrings
{
    // 이름 키(영어 원문이 아닌 것)의 영어 문안
    public static readonly Dictionary<string, string> EnglishOverrides = new()
    {
        ["FooterCodex"] = " - OpenAI's AI coding assistant",
        ["FooterClaude"] = " - Anthropic's Claude Code CLI",
        ["FooterCopilot"] = " - GitHub's AI coding assistant",
        ["FooterGemini"] = " - Google's Gemini CLI",
    };

    public static readonly Dictionary<string, string> Korean = new()
    {
        // 팝업
        ["AI Usage Monitor"] = "AI 통합 사용량 모니터",
        ["FooterCodex"] = " - OpenAI 의 AI 코딩 도구",
        ["FooterClaude"] = " - Anthropic 의 Claude Code CLI",
        ["FooterCopilot"] = " - GitHub 의 AI 코딩 도구",
        ["FooterGemini"] = " - Google 의 Gemini CLI",
        ["Pro models · daily"] = "Pro 모델 · 일일",
        ["Flash models · daily"] = "Flash 모델 · 일일",
        ["No Gemini usage data available"] = "Gemini 사용량 데이터 없음",
        ["Gemini disabled in Settings"] = "설정에서 Gemini 가 꺼져 있음",
        ["Show Gemini CLI usage"] = "Gemini CLI 사용량 표시",
        ["Reads ~/.gemini: quota from the signed-in Code Assist seat, tokens and cost from session logs."] = "~/.gemini 읽기\n한도: Code Assist 좌석 · 토큰·비용: 세션 로그",
        ["Quota needs a Code Assist Standard/Enterprise seat. Personal Google sign-in was closed on 2026-06-18, so only token and cost history shows for it. Cost is an API-price estimate."] = "한도: Code Assist Standard/Enterprise 좌석 필요 · 개인 Google 로그인: 토큰·비용만(2026-06-18 차단) · 비용: API 단가 추정",
        ["Gemini CLI login on this PC · {0}"] = "이 PC 의 Gemini CLI 로그인 · {0}",
        ["Session"] = "세션",
        ["Weekly"] = "주간",
        ["Premium requests"] = "프리미엄 요청",
        ["Chat requests"] = "채팅 요청",
        ["Cost"] = "비용",
        ["Today:"] = "오늘:",
        ["Today"] = "오늘",
        ["Last 30 days:"] = "최근 30일:",
        ["Last {0} days:"] = "최근 {0}일:",
        ["Last 1 year:"] = "최근 1년:",
        ["Daily avg:"] = "일 평균:",
        ["Close settings"] = "설정 닫기",
        ["Close"] = "닫기",
        ["Back"] = "돌아가기",
        ["Cancel"] = "취소",
        ["Apply code"] = "코드 적용",
        ["Paste the code the browser shows after signing in"] = "로그인 후 브라우저에 표시된 코드 붙여넣기",
        ["Finish signing in to \"{0}\" in the browser. If it shows a code, paste it below."] = "① 브라우저에서 로그인\n② 코드가 나오면 복사해 아래 칸에 붙여넣기\n③ 「코드 적용」 누르기",
        ["Finish signing in to \"{0}\" in the browser."] = "브라우저에서 로그인",
        ["Code sent. Waiting for sign-in to finish..."] = "코드를 보냈습니다. 로그인이 끝나기를 기다리는 중입니다…",
        ["Another sign-in is still in progress. Finish or cancel it first."] = "다른 로그인이 아직 진행 중입니다. 먼저 마치거나 취소해 주십시오.",
        ["Next refresh {0} · in {1}"] = "다음 갱신 {0} · {1} 후",
        ["Next {0} · in {1}"] = "다음 {0} · {1} 후",
        ["Weekly · per model"] = "주간 · 모델별",
        ["This week:"] = "이번 주:",
        [" tokens"] = " 토큰",
        ["All Profiles"] = "전체 계정",
        ["Chart range"] = "차트 기간",
        ["Settings"] = "설정",
        ["Switch light / dark"] = "라이트 / 다크 전환",
        ["Refresh now"] = "지금 새로고침",
        ["View Claude usage"] = "Claude 사용량 보기",
        ["View Codex usage on ChatGPT"] = "ChatGPT 에서 Codex 사용량 보기",
        ["View Copilot usage on GitHub"] = "GitHub 에서 Copilot 사용량 보기",
        ["+ Add account…"] = "+ 계정 추가…",
        ["This PC"] = "이 PC",
        ["All"] = "전체",
        ["Every account, stacked"] = "모든 계정을 한 화면에",
        ["All · {0} accounts"] = "전체 · 계정 {0}개",
        ["Weekly · {0}"] = "주간 · {0}",
        ["Theme"] = "테마",
        ["Display"] = "화면",
        ["General"] = "일반",
        ["About"] = "정보",
        ["Daily cost"] = "일별 비용",
        ["Weekly cost"] = "주별 비용",
        ["Monthly cost"] = "월별 비용",
        ["total {0} · peak {1}"] = "합계 {0} · 최고 {1}",
        ["total {0} · best day {1}"] = "합계 {0} · 일 최고 {1}",
        ["total {0} · best week {1}"] = "합계 {0} · 주 최고 {1}",
        ["total {0} · best month {1}"] = "합계 {0} · 월 최고 {1}",
        ["Token types · {0} days"] = "토큰 유형 · {0}일",
        ["Token types · 1 year"] = "토큰 유형 · 1년",
        ["mo"] = "월",
        ["d"] = "일",
        ["Value:"] = "활용도:",
        ["{0}x"] = "{0}배",
        ["Low"] = "낮음",
        ["Fair"] = "보통",
        ["Good"] = "좋음",
        ["Great"] = "매우 좋음",
        ["Max"] = "최대",
        ["Grade bounds {0}x (Settings › General)"] = "등급 경계 {0}배 (설정 › 일반)",
        ["Source"] = "출처",
        ["Fee set in Settings › Accounts"] = "설정 › 계정에서 적은 요금",
        ["Tier not reported"] = "등급 정보 없음 · 설정 › 계정에서 요금 입력",
        ["Monthly billing"] = "월납 기준",
        ["Standard seat, monthly billing — the API does not report seat type"] = "추정 · Standard 좌석 월납 · 설정 › 계정에서 변경",
        ["Contract pricing"] = "계약 요금 · 설정 › 계정에서 입력",
        ["No subscriptionType in credentials"] = "플랜 정보 없음 · 설정 › 계정에서 요금 입력",
        ["Rates $/MTok"] = "단가 $/M토큰",
        ["Order: input · output · cache read · cache write"] = "순서: 입력 · 출력 · 캐시 읽기 · 캐시 쓰기",
        ["estimated (model not in rate table)"] = "추정 (단가표에 없는 모델)",
        ["{0} untyped tokens at recorded cost"] = "유형 미상 {0} 토큰은 기록값",
        ["recorded {0}, older rates"] = "기록 {0} (옛 단가)",
        ["Value grade bounds (×)"] = "활용도 등급 경계 (배)",
        ["Four ascending multiples. Below the 1st = Low, above the 4th = Max."] = "오름차순 배수 4개\n1번째 미만 낮음 · 4번째 이상 최대",
        ["Low · Fair · Good · Great · Max — default 1, 3, 10, 20"] = "낮음 · 보통 · 좋음 · 매우 좋음 · 최대 — 기본 1, 3, 10, 20",
        ["Monthly fee in USD. Blank = from plan."] = "월 구독료(USD) · 비우면 플랜 기준",
        ["Type"] = "유형",
        ["Fee $/mo"] = "월 요금 $",
        ["Name (8 chars)"] = "명칭 (8자)",
        ["e.g. Work"] = "예: 회사",
        ["auto"] = "자동",
        ["Name shown in popup"] = "팝업에 보일 이름",
        ["Suggest an improvement"] = "개선 제안",
        ["Diagnostics"] = "진단 정보",
        ["Keep usage events"] = "사용 기록 남기기 (갱신 · 오류 · 연동)",
        ["Keep usage log"] = "사용 정보 수집",
        ["Keeps refresh · error · link events on this PC. Nothing is sent anywhere."] = "갱신·오류·연동 기록을 이 PC 에만\n자동 전송 없음",
        ["Open issue"] = "이슈 열기",
        ["Save file"] = "파일로 저장",
        ["Copy"] = "복사",
        ["Copied — paste it into the issue"] = "복사했습니다 — 이슈에 붙여 넣어 주십시오",
        ["Copied — paste it into the issue body"] = "진단 정보를 복사했습니다 — 이슈 본문에 붙여 넣어 주십시오",
        ["Copies the diagnostics, then opens a new GitHub issue"] = "진단 정보 복사 후 GitHub 이슈 열기",
        ["Open issue copies the diagnostics · emails masked · no tokens"] = "「이슈 열기」가 진단 정보를 복사합니다 · 메일은 가림 · 토큰 없음",
        ["Saved — attach it to the issue"] = "저장했습니다 — 이슈에 첨부해 주십시오",
        ["Emails masked · no tokens · attach the file to the issue"] = "메일은 가림 · 토큰 없음 · 저장한 파일을 이슈에 첨부",
        ["Programs · {0} days"] = "프로그램 · {0}일",
        ["Programs · 1 year"] = "프로그램 · 1년",
        ["Agent mode"] = "에이전트 모드",
        ["Unknown program"] = "프로그램 미상",
        ["History without program info (older or extra-account folder)"] = "프로그램 정보 없는 이력 (옛 이력 · 추가 계정 폴더)",
        ["Input"] = "입력",
        ["Output"] = "출력",
        ["Cache read"] = "캐시 읽기",
        ["Cache write"] = "캐시 쓰기",
        ["Unknown"] = "유형 미상",
        ["Fresh input sent to the model (not cached)"] = "모델에 새로 보낸 입력(캐시 아님)",
        ["Text the model generated"] = "모델이 생성한 출력",
        ["Input re-read from the prompt cache (cheapest)"] = "프롬프트 캐시에서 다시 읽은 입력(가장 저렴)",
        ["Input stored into the prompt cache"] = "프롬프트 캐시에 저장한 입력",
        ["Older history saved before token types were recorded"] = "토큰 유형을 기록하기 전에 쌓인 옛 이력",
        ["Models · {0} days"] = "모델 · {0}일",
        ["Models · 1 year"] = "모델 · 1년",
        ["Others ({0})"] = "그 외 ({0})",
        ["{0} tokens"] = "{0} 토큰",
        ["unknown"] = "알 수 없음",
        ["Updated {0}"] = "{0} 갱신",
        ["Updated never"] = "갱신 전",
        ["Never"] = "없음",
        ["1y"] = "1년",
        ["{0}d"] = "{0}일",

        // 상태
        ["No data"] = "데이터 없음",
        ["No Claude usage data available"] = "Claude 사용량 데이터 없음",
        ["No Codex usage data available"] = "Codex 사용량 데이터 없음",
        ["No Copilot usage data available"] = "Copilot 사용량 데이터 없음",
        ["Copilot disabled in Settings"] = "설정에서 Copilot 이 꺼져 있음",
        ["Copilot usage unavailable"] = "Copilot 사용량을 가져올 수 없음",
        ["Not signed in"] = "로그인되지 않음",
        ["Unable to read account"] = "계정을 읽을 수 없음",
        ["API key"] = "API 키",

        // 설정 창
        ["Accounts"] = "계정",
        ["Extra Claude accounts (usage only)"] = "추가 Claude 계정 (사용량 조회 전용)",
        ["Remove"] = "삭제",
        ["Sign in"] = "로그인",
        ["Add account"] = "계정 추가",
        ["Email or a short name for the account"] = "계정 이메일 또는 짧은 이름",
        ["Enter the account's email or a short name."] = "계정 이메일이나 짧은 이름을 적어 주십시오.",
        ["✓ \"{0}\" signed in as {1}. Restart to show its usage."] = "✓ \"{0}\" 이(가) {1} 로 로그인되었습니다. 다시 시작하면 사용량이 보입니다.",
        ["✓ \"{0}\" signed in as {1}. Restarting to show its usage..."] = "✓ \"{0}\" 이(가) {1} 로 로그인되었습니다. 계정 목록에 넣으려고 앱을 다시 시작합니다...",
        ["Sign out"] = "로그아웃",
        ["Default"] = "기본",
        ["Personal"] = "개인",
        ["Work"] = "회사",
        ["Team"] = "팀",
        ["Test"] = "테스트",
        ["Name · Type"] = "명칭 · 유형",
        ["Current"] = "현재",
        ["GitHub releases"] = "GitHub 릴리스",
        ["GitHub latest {0}"] = "GitHub 최신 {0}",
        ["No release on GitHub yet"] = "GitHub 에 아직 릴리스가 없습니다",
        ["A newer version is available."] = "새 버전이 있습니다.",
        ["This build is newer than the latest release."] = "지금 버전이 공개된 최신 릴리스보다 높습니다.",
        ["Could not read GitHub releases."] = "GitHub 릴리스를 읽지 못했습니다.",
        ["Install this version"] = "이 버전 설치",
        ["Copy setup file link — anyone you send it to gets the latest setup file"] = "설치 파일 주소 복사\n받은 사람이 최신본을 내려받습니다",
        ["Copied the setup file link"] = "설치 파일 주소를 복사했습니다",
        ["Copy winget command — paste it into a terminal; installs without the SmartScreen prompt"] = "winget 설치 명령 복사\n터미널에 붙여 넣으면 SmartScreen 창 없이",
        ["Copied the winget command"] = "winget 설치 명령을 복사했습니다",
        ["Author email"] = "제작자 메일",
        ["Share the app"] = "앱 공유하기",
        ["Author email — click to copy the address"] = "제작자 메일 — 클릭하면 주소를 복사합니다",
        ["Copied the author's email address"] = "제작자 메일 주소를 복사했습니다",
        ["Download setup file — the latest installer, via your browser"] = "설치 파일 내려받기\n최신 설치 관리자를 브라우저로",
        ["Open repository"] = "저장소 열기",
        ["Installing a version works only in the installed app, not in a development build."] = "설치본 전용 — 개발 빌드는 비교만",
        ["Downloading {0}..."] = "{0} 을(를) 받는 중입니다...",
        ["Downloading {0}... {1} / {2} MB ({3}%)"] = "{0} 받는 중... {1} / {2} MB ({3}%)",
        ["Downloading {0}... {1} MB"] = "{0} 받는 중... {1} MB",
        ["Verifying the download..."] = "받은 파일을 검증하는 중...",
        ["Unpacking {0}..."] = "{0} 압축을 푸는 중...",
        ["Installing {0}..."] = "{0} 설치하는 중...",
        ["Installed {0}. The app restarts in a moment."] = "{0} 설치를 마쳤습니다. 잠시 뒤 앱이 다시 시작됩니다.",
        ["Automatic update"] = "자동 업데이트",
        ["Notify before installing"] = "적용 전 알림",
        ["Checks for a new version at the set time and installs it. The app restarts by itself."] = "정한 시각에 새 버전 확인·설치\n앱이 스스로 다시 시작합니다",
        ["Time to install, by this PC clock (HH:mm)."] = "설치할 시각 — 이 PC 시간(HH:mm)",
        ["Shows a tray notice 1 minute before installing. Turn automatic update off within that minute to cancel."] = "설치 1분 전 트레이 알림\n그 사이에 끄면 설치하지 않습니다",
        ["Automatic update runs only in the installed app."] = "자동 업데이트는 설치본에서만 동작합니다.",
        ["Enter the time as HH:mm (e.g. 04:00)."] = "시각을 HH:mm 으로 적어 주십시오(예: 04:00).",
        ["Next automatic update: {0}"] = "다음 자동 업데이트: {0}",
        ["Updating to {0} in 1 minute. The app restarts by itself."] = "1분 뒤 {0} 으로 업데이트합니다. 앱은 스스로 다시 시작됩니다.",
        ["Scheduled update was cancelled."] = "예약된 업데이트를 취소했습니다.",
        ["Installing {0}. The app will restart."] = "{0} 을(를) 설치합니다. 앱이 다시 시작됩니다.",
        ["Could not install {0}."] = "{0} 설치에 실패했습니다.",
        ["App settings"] = "앱 설정",
        ["Accounts & AI tools"] = "계정 · AI 도구",
        ["AI tools"] = "AI 도구",
        ["Edit"] = "편집",
        ["Drag to change the order"] = "끌어서 순서를 바꿉니다",
        ["Move up"] = "위로",
        ["Move down"] = "아래로",
        ["Account name shown in the popup (up to 8 characters)"] = "팝업에 보일 계정 명칭(최대 8자)",
        ["No Claude token on this PC — sign in from Settings › Accounts"] = "이 PC 에 Claude 토큰이 없습니다 — 설정 › 계정에서 로그인하십시오",
        ["Icon"] = "아이콘",
        ["Tray icon"] = "트레이 아이콘",
        ["Bars"] = "막대",
        ["Ring"] = "링",
        ["Sparkle"] = "반짝임",
        ["Drawing {0}"] = "그림 {0}",
        ["Image {0}"] = "이미지 {0}",
        ["+ Draw"] = "+ 그리기",
        ["+ Image"] = "+ 불러오기",
        ["New icon"] = "새 아이콘 그리기",
        ["Delete this icon"] = "이 아이콘 삭제",
        ["Could not delete that icon: {0}"] = "아이콘을 지우지 못했습니다: {0}",
        ["Saving adds a new icon. Existing icons are not changed."] = "저장 = 새 아이콘 추가 · 기존 아이콘 유지",
        ["New account"] = "새 계정",
        ["Add account (browser sign-in)"] = "계정 추가 (브라우저 연동)",
        ["The account you pick in the browser is added. Its email and token are checked afterwards."] = "브라우저에서 고른 계정 연동 · 연동 후 메일·토큰 확인",
        ["Program links"] = "프로그램 연동",
        ["Usage from each program on this PC is counted for the account you pick here. Past logs follow the change too."] = "프로그램별 기록을 셀 계정 · 지난 기록 포함",
        ["Desktop app"] = "데스크톱 앱",
        ["VS Code"] = "VS Code",
        ["Terminal CLI"] = "터미널 CLI",
        ["Link"] = "연동",
        ["Linked"] = "연동됨",
        ["GitHub personal access token"] = "GitHub 개인 액세스 토큰",
        ["The token is managed in Accounts › Copilot."] = "토큰 관리: 「계정 › Copilot」",
        ["The sign-in is shown in Accounts › Gemini."] = "로그인 상태: 「계정 › Gemini」",
        ["Needs linking"] = "연동 필요",
        ["Relink"] = "다시 연동",
        ["Unlink"] = "연동 해제",
        ["Link an account to this slot — sign in in the browser."] = "브라우저 로그인으로 이 자리에 계정 연동",
        ["Wrong account? Sign in again and pick another one (the login window lets you pick any account)."] = "계정이 틀리면 다시 로그인\n전용 창에서 다른 계정 선택",
        ["Open in browser"] = "브라우저로 열기",
        ["Login window"] = "전용 로그인 창",
        ["Copy address"] = "주소 복사",
        ["Opens a separate Chrome window with no saved sign-in, so you can pick any account. It closes when linking finishes."] = "로그인 기록 없는 Chrome 창\n계정 자유 선택 · 끝나면 닫힘",
        ["Copied the sign-in address. Paste it into any browser."] = "로그인 주소를 복사했습니다. 아무 브라우저에 붙여 넣으십시오.",
        ["Chrome was not found. Use Copy address and open a private window yourself."] = "Chrome 을 찾지 못했습니다. 「주소 복사」 후 시크릿 창에 직접 붙여 넣으십시오.",
        ["Signed in as {0}, but no token was saved. Link again."] = "{0} 로 로그인됐지만 토큰이 저장되지 않았습니다. 다시 연동하십시오.",
        ["{0} is already linked to \"{1}\". Use Relink on this slot and pick another account (the login window helps)."] = "{0} 은(는) 이미 「{1}」 자리에 연동돼 있습니다. 이 자리에서 「다시 연동」으로 다른 계정을 고르십시오(전용 로그인 창 추천).",
        ["✓ \"{0}\" relinked: {1} → {2} (token saved)."] = "✓ 「{0}」 다시 연동: {1} → {2} (토큰 저장됨).",
        ["✓ \"{0}\" linked to {1} (token saved)."] = "✓ 「{0}」 연동됨: {1} (토큰 저장됨).",
        ["Linking \"{0}\" was not completed. Press Link to try again."] = "「{0}」 연동이 끝나지 않았습니다. 「연동」을 눌러 다시 하십시오.",
        ["Restarting to show its usage..."] = "사용량을 띄우려고 다시 시작합니다…",
        ["Could not open the browser: {0}"] = "브라우저를 열지 못했습니다: {0}",
        ["Which code? After you click Authorize in the browser, claude.ai shows an Authentication Code — copy it and paste it below. If the browser finishes by itself, no code is needed."] = "코드 찾는 순서\n① 브라우저에서 「Authorize」 클릭\n② claude.ai 의 「Authentication Code」 복사\n③ 아래 칸에 붙여넣기\n※ 브라우저가 자동 완료하면 불필요",
        ["Images"] = "그림",
        ["Could not read that image: {0}"] = "그림을 읽지 못했습니다: {0}",
        ["Could not save the drawing: {0}"] = "그림을 저장하지 못했습니다: {0}",
        ["Letter"] = "글자색",
        ["Accent"] = "강조색",
        ["Background top"] = "바탕(위)",
        ["Background bottom"] = "바탕(아래)",
        ["Black"] = "검정",
        ["Eraser"] = "지우개",
        ["Start from"] = "시작 그림",
        ["Blank tile"] = "바탕만",
        ["Click or drag to paint. The icon follows the theme colors."] = "클릭·드래그로 칠하기 · 기본 모양은 테마 색",
        ["Signed in, but no token on this PC — sign in again"] = "로그인 정보는 있으나 토큰이 없음 — 다시 로그인",
        ["Always show icon on taskbar"] = "작업 표시줄에 아이콘 항상 표시",
        ["Keep the icon on the taskbar instead of the hidden icons (^), so one click opens the popup."] = "숨김 아이콘(^) 대신 작업 표시줄에 고정\n클릭 한 번으로 팝업",
        ["All accounts, last 7 days:"] = "전체 계정 최근 7일:",
        ["All accounts · cost"] = "전체 비용",
        ["New VS Code and CLI sessions are counted for the account signed in on this PC at that time. The table below applies to older sessions."] = "새 VS Code·CLI 세션: 당시 로그인 계정 · 아래 표: 그 전 기록 전용",
        ["Account name shown in the popup"] = "팝업에 보일 계정 명칭",
        ["Account type — type freely or pick one. Default is shown first when the popup opens."] = "계정 유형 — 입력 또는 선택\n「기본」이 팝업 첫 화면",
        ["Sign out of \"{0}\" on this PC? The {0} CLI in your terminal will be signed out too."] = "이 PC 의 \"{0}\" 로그인을 해제할까요? 터미널의 {0} CLI 도 함께 로그아웃됩니다.",
        ["Could not sign out of \"{0}\": {1}"] = "\"{0}\" 로그아웃에 실패했습니다: {1}",
        ["✓ Signed out of \"{0}\"."] = "✓ \"{0}\" 에서 로그아웃했습니다.",
        ["✓ \"{0}\" signed in as {1}. Refreshing usage now."] = "✓ \"{0}\" 이(가) {1} 로 로그인되었습니다. 사용량을 새로 읽는 중입니다.",
        ["Restart app to apply"] = "앱을 다시 시작해 적용",
        ["SYSTEM"] = "시스템",
        ["Start at login"] = "로그인 시 자동 실행",
        ["Refresh when opened"] = "열 때마다 새로고침",
        ["Fetch usage again every time the popup opens. Off: only the background interval refreshes."] = "팝업을 열 때마다 재조회 · 끄면 주기 갱신만",
        ["Automatically launch AI Usage Monitor when Windows starts."] = "Windows 시작 시 자동 실행",
        ["Language"] = "언어",
        ["AUTOMATION"] = "자동화",
        ["Refresh interval"] = "새로고침 주기",
        ["Popup size"] = "팝업 크기",
        ["New version downloaded. Press the Install button below to apply."] = "새 버전을 받아 두었습니다 — 아래 「이 버전 설치」를 누르면 적용됩니다.",
        ["Recommended — the default (A for AI)."] = "권장 — 기본 단축키입니다(A = AI).",
        ["Restore defaults"] = "기본값으로",
        ["Restores only this tab"] = "이 탭의 설정만 되돌립니다",
        ["Restored to defaults."] = "기본값으로 되돌렸습니다.",
        ["Move to default position"] = "기본 위치로 이동",
        ["Reset settings..."] = "설정 초기화...",
        ["Restore every setting to its default?"] = "모든 설정을 기본값으로 되돌릴까요?",
        ["Accounts, linking and usage history are kept."] = "계정·연동·사용량 이력은 그대로 둡니다.",
        ["Auto"] = "자동",
        ["Scales the popup width and text together. Auto uses your screen size."] = "폭과 글자를 함께 키웁니다\n「자동」은 화면 크기에 맞춰",
        ["How often AI Usage Monitor polls for usage data in the background."] = "백그라운드 조회 주기",
        ["Popup shortcut {0}"] = "팝업 단축키 {0}",
        ["+ Add shortcut"] = "단축키 추가",
        ["Already set as another popup shortcut."] = "다른 팝업 단축키와 중복",
        ["Click the box, then press the keys together."] = "입력란 클릭 → 키 조합 누르기",
        ["Ctrl+Alt+F1–F12 is recommended. Blocked: one-modifier keys (Ctrl+C, Alt+F4), Win combinations, and Esc·Tab·Delete·arrow keys."] = "권장: Ctrl+Alt+A · Ctrl+Alt+F1~F12\n차단: 수정키 하나(Ctrl+C) · Win 조합 · Esc·Tab·방향키",
        ["Press a letter, number or F1–F12 together with Ctrl and Alt."] = "Ctrl+Alt + 글자·숫자·F1~F12",
        ["Win key combinations are reserved by Windows."] = "Win 조합 — Windows 예약",
        ["Esc, Tab, Space, Enter, Delete, arrows and other editing keys are used by Windows and apps."] = "Esc·Tab·Space·Enter·Delete·방향키 — 편집 키라 불가",
        ["Include Ctrl or Alt — Shift alone just types the character."] = "Ctrl 또는 Alt 필요 — Shift 단독 불가",
        ["A single modifier (like Ctrl+C or Alt+F4) clashes with app shortcuts. Use two, e.g. Ctrl+Alt."] = "수정키 하나 — 프로그램 단축키와 충돌 · Ctrl+Alt 처럼 둘 사용",
        ["Recommended — Windows and common apps rarely use Ctrl+Alt+F1–F12."] = "권장 키 · 적용·저장됨",
        ["Applied, but browsers and VS Code use many Ctrl+Shift / Alt+Shift letters (e.g. Ctrl+Shift+T, P, N)."] = "적용·저장됨 · 주의: 브라우저·VS Code 가 Ctrl+Shift·Alt+Shift 조합 사용",
        ["Applied."] = "적용·저장됨",
        ["Change"] = "변경",
        ["Press Save to apply."] = "「저장」을 누르면 적용",
        ["Press the keys, then Save."] = "키 조합 입력 → 「저장」",
        ["Another program already uses this shortcut. Pick another one."] = "다른 프로그램이 사용 중 — 다른 키 선택",
        ["CLAUDE CODE"] = "CLAUDE CODE",
        ["Use multicc profiles"] = "여러 계정 함께 보기",
        ["Automatically detect and display all multicc profiles in the Claude tab."] = "등록된 계정을 Claude 탭에 모두 표시",
        ["Profiles found:"] = "등록된 계정:",
        ["multicc not detected. Install multicc to manage multiple Claude Code accounts."] = "추가 계정 없음 — 위 「계정」에서 추가",
        ["COPILOT"] = "COPILOT",
        ["Enable GitHub Copilot usage"] = "GitHub Copilot 사용량 표시",
        ["Connect a GitHub personal access token to fetch usage data."] = "GitHub 개인 액세스 토큰으로 사용량 조회",
        ["Personal access token"] = "개인 액세스 토큰",
        ["Save token"] = "토큰 저장",
        ["Clear token"] = "토큰 지우기",
        ["UPDATES"] = "업데이트",
        ["Check for updates"] = "업데이트 확인",
        ["Version"] = "버전",
        ["Changes are saved automatically."] = "변경 사항은 자동으로 저장됩니다.",
        ["Made by"] = "제작",
        ["Save"] = "저장",
        ["Clear"] = "지우기",
        ["Claude Code login on this PC · {0}"] = "이 PC 의 Claude Code 로그인 · {0}",
        ["Codex CLI login on this PC · {0}"] = "이 PC 의 Codex CLI 로그인 · {0}",
        ["\"{0}\" already exists."] = "\"{0}\" 은(는) 이미 있습니다.",
        ["Finish signing in to \"{0}\" in the browser. If no browser opens, use the minimized terminal on the taskbar."] = "① 브라우저에서 로그인\n② 브라우저가 안 열리면 작업 표시줄의 최소화된 터미널 열기",
        ["Extra Claude account (usage only) — email or a short name"] = "추가 Claude 계정(사용량 조회 전용) — 이메일 또는 짧은 이름",
        ["Extra Codex account (usage only) — email or a short name"] = "추가 Codex 계정(사용량 조회 전용) — 이메일 또는 짧은 이름",
        ["Sign-in to \"{0}\" was not completed."] = "\"{0}\" 로그인이 완료되지 않았습니다.",
        ["Could not start sign-in: {0}"] = "로그인을 시작하지 못했습니다: {0}",
        ["{0} CLI was not found on this PC. Install it, then try again."] = "이 PC 에서 {0} CLI 를 찾지 못했습니다. 설치한 뒤 다시 시도해 주십시오.",
        ["Opens the official CLI sign-in in your browser. Signing in again switches the account."] = "공식 CLI 로그인을 브라우저로 열기 · 재로그인 시 계정 전환",
        ["Removed \"{0}\". Restart to apply."] = "\"{0}\" 을(를) 삭제했습니다. 앱을 다시 시작하면 적용됩니다.",
        ["Could not remove \"{0}\": {1}"] = "\"{0}\" 을(를) 삭제하지 못했습니다: {1}",
        ["Restart required to apply changes."] = "앱을 다시 시작해야 적용됩니다.",
        ["Copilot token is required."] = "Copilot 토큰을 입력해 주십시오.",
        ["Copilot token saved."] = "Copilot 토큰을 저장했습니다.",
        ["Could not save Copilot token."] = "Copilot 토큰을 저장하지 못했습니다.",
        ["Copilot token cleared."] = "Copilot 토큰을 지웠습니다.",
        ["Could not clear Copilot token."] = "Copilot 토큰을 지우지 못했습니다.",
        ["Copilot token not set."] = "Copilot 토큰이 설정되지 않았습니다.",
        ["Could not load Copilot token."] = "Copilot 토큰을 불러오지 못했습니다.",
        ["Copilot token not configured."] = "Copilot 토큰이 설정되지 않았습니다.",
        ["Copilot token rejected."] = "Copilot 토큰이 거부되었습니다.",
        ["Copilot access denied for this token."] = "이 토큰은 Copilot 접근 권한이 없습니다.",
        ["Copilot usage endpoint unavailable or token lacks Copilot access."] = "Copilot 사용량을 조회할 수 없거나 토큰에 권한이 없습니다.",
        ["Copilot usage rate limited."] = "Copilot 사용량 조회가 일시적으로 제한되었습니다.",
        ["Copilot usage request failed."] = "Copilot 사용량 요청에 실패했습니다.",
        ["Copilot usage response could not be parsed."] = "Copilot 사용량 응답을 해석하지 못했습니다.",
        ["Updates are not available."] = "업데이트를 사용할 수 없습니다.",
        ["Checking for updates..."] = "업데이트 확인 중...",
        ["Update found. Restarting..."] = "업데이트를 찾았습니다. 다시 시작합니다...",
        ["Update staged. Restart to apply."] = "업데이트가 준비되었습니다. 다시 시작하면 적용됩니다.",
        ["You're up to date."] = "최신 버전입니다.",
        ["Update check already in progress."] = "이미 업데이트를 확인하는 중입니다.",
        ["Could not check for updates."] = "업데이트를 확인하지 못했습니다.",
        ["Update check timed out. Try again."] = "업데이트 확인 시간이 초과되었습니다. 다시 시도해 주십시오.",

        // 트레이 메뉴
        ["Show Widget"] = "열기",
        ["Refresh Now"] = "지금 새로고침",
        ["Settings..."] = "설정...",
        ["Exit"] = "종료",
    };

    /// <summary>
    /// 코어·인프라 층이 만든 가변 문장 — 원문 형식은 costats.Core/Pulse/UsageFormatter.cs 가 정한다.
    /// </summary>
    public static readonly (Regex Pattern, Func<Match, string> Replace)[] KoreanPatterns =
    [
        (new Regex(@"^Resets now$"), _ => "곧 초기화"),
        (new Regex(@"^Resets in (.+)$"), m => $"{Loc.Duration(m.Groups[1].Value)} 후 초기화"),
        (new Regex(@"^Pace: (.+?)(?: · (.+))?$"), m => m.Groups[2].Success
            ? $"페이스: {Pace(m.Groups[1].Value)} · {Pace(m.Groups[2].Value)}"
            : $"페이스: {Pace(m.Groups[1].Value)}"),
        (new Regex(@"^(\d+)% used$"), m => $"{m.Groups[1].Value}% 사용"),
        (new Regex(@"^Updated just now$"), _ => "방금 갱신"),
        (new Regex(@"^Updated less than a minute ago$"), _ => "1분 이내 갱신"),
        (new Regex(@"^Updated (\d+[mhd]) ago$"), m => $"{Loc.Duration(m.Groups[1].Value)} 전 갱신"),
        (new Regex(@"^No data for (.+)$"), m => $"{m.Groups[1].Value} 데이터 없음"),
        (new Regex(@"^Overage: (.+) / (.+)$"), m => $"초과 사용: {m.Groups[1].Value} / {m.Groups[2].Value}"),
        (new Regex(@"^Balance: (.+) remaining$"), m => $"잔액: {m.Groups[1].Value}"),
        (new Regex(@"^(.+) today  ·  (.+) / 30d$"), m => $"오늘 {m.Groups[1].Value}  ·  30일 {m.Groups[2].Value}"),
        (new Regex(@"^(\d+) profiles  ·  (\d+) at limit, (\d+) warning$"), m => $"계정 {m.Groups[1].Value}개  ·  한도 도달 {m.Groups[2].Value}, 주의 {m.Groups[3].Value}"),
        (new Regex(@"^(\d+) profiles  ·  (\d+) near limit$"), m => $"계정 {m.Groups[1].Value}개  ·  한도 근접 {m.Groups[2].Value}"),
        (new Regex(@"^(\d+) profiles  ·  All healthy$"), m => $"계정 {m.Groups[1].Value}개  ·  모두 정상"),
        (new Regex(@"^(\d+) profiles  ·  (\d+) need linking$"), m => $"계정 {m.Groups[1].Value}개  ·  연동 필요 {m.Groups[2].Value}"),
    ];

    private static string Pace(string part)
    {
        var match = Regex.Match(part, @"^(\d+)% in (deficit|reserve)$");
        if (match.Success)
        {
            return match.Groups[2].Value == "deficit" ? $"{match.Groups[1].Value}% 초과" : $"{match.Groups[1].Value}% 여유";
        }

        match = Regex.Match(part, @"^Runs out in (.+)$");
        if (match.Success)
        {
            return $"{Loc.Duration(match.Groups[1].Value)} 후 소진";
        }

        return part switch
        {
            "On pace" => "적정",
            "Unknown" => "알 수 없음",
            "Lasts until reset" => "초기화까지 충분",
            "Runs out now" => "곧 소진",
            _ => part
        };
    }
}
